/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_openal_ALC */

#ifndef _Included_org_lwjgl_openal_ALC
#define _Included_org_lwjgl_openal_ALC
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_openal_ALC_ALC_INVALID
#define org_lwjgl_openal_ALC_ALC_INVALID -1L
#undef org_lwjgl_openal_ALC_ALC_FALSE
#define org_lwjgl_openal_ALC_ALC_FALSE 0L
#undef org_lwjgl_openal_ALC_ALC_TRUE
#define org_lwjgl_openal_ALC_ALC_TRUE 1L
#undef org_lwjgl_openal_ALC_ALC_NO_ERROR
#define org_lwjgl_openal_ALC_ALC_NO_ERROR 0L
#undef org_lwjgl_openal_ALC_ALC_MAJOR_VERSION
#define org_lwjgl_openal_ALC_ALC_MAJOR_VERSION 4096L
#undef org_lwjgl_openal_ALC_ALC_MINOR_VERSION
#define org_lwjgl_openal_ALC_ALC_MINOR_VERSION 4097L
#undef org_lwjgl_openal_ALC_ALC_ATTRIBUTES_SIZE
#define org_lwjgl_openal_ALC_ALC_ATTRIBUTES_SIZE 4098L
#undef org_lwjgl_openal_ALC_ALC_ALL_ATTRIBUTES
#define org_lwjgl_openal_ALC_ALC_ALL_ATTRIBUTES 4099L
#undef org_lwjgl_openal_ALC_ALC_DEFAULT_DEVICE_SPECIFIER
#define org_lwjgl_openal_ALC_ALC_DEFAULT_DEVICE_SPECIFIER 4100L
#undef org_lwjgl_openal_ALC_ALC_DEVICE_SPECIFIER
#define org_lwjgl_openal_ALC_ALC_DEVICE_SPECIFIER 4101L
#undef org_lwjgl_openal_ALC_ALC_EXTENSIONS
#define org_lwjgl_openal_ALC_ALC_EXTENSIONS 4102L
#undef org_lwjgl_openal_ALC_ALC_FREQUENCY
#define org_lwjgl_openal_ALC_ALC_FREQUENCY 4103L
#undef org_lwjgl_openal_ALC_ALC_REFRESH
#define org_lwjgl_openal_ALC_ALC_REFRESH 4104L
#undef org_lwjgl_openal_ALC_ALC_SYNC
#define org_lwjgl_openal_ALC_ALC_SYNC 4105L
#undef org_lwjgl_openal_ALC_ALC_INVALID_DEVICE
#define org_lwjgl_openal_ALC_ALC_INVALID_DEVICE 40961L
#undef org_lwjgl_openal_ALC_ALC_INVALID_CONTEXT
#define org_lwjgl_openal_ALC_ALC_INVALID_CONTEXT 40962L
#undef org_lwjgl_openal_ALC_ALC_INVALID_ENUM
#define org_lwjgl_openal_ALC_ALC_INVALID_ENUM 40963L
#undef org_lwjgl_openal_ALC_ALC_INVALID_VALUE
#define org_lwjgl_openal_ALC_ALC_INVALID_VALUE 40964L
#undef org_lwjgl_openal_ALC_ALC_OUT_OF_MEMORY
#define org_lwjgl_openal_ALC_ALC_OUT_OF_MEMORY 40965L
/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    initNativeStubs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_ALC_initNativeStubs
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    nalcGetString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_openal_ALC_nalcGetString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    nalcGetIntegerv
 * Signature: (JIILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_ALC_nalcGetIntegerv
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    alcOpenDevice
 * Signature: (Ljava/lang/String;)Lorg/lwjgl/openal/ALCdevice;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_openal_ALC_alcOpenDevice
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    alcCloseDevice
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_ALC_alcCloseDevice
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    nalcCreateContext
 * Signature: (JLjava/nio/IntBuffer;)Lorg/lwjgl/openal/ALCcontext;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_openal_ALC_nalcCreateContext
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    alcMakeContextCurrent
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_openal_ALC_alcMakeContextCurrent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    nalcProcessContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_ALC_nalcProcessContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    alcGetCurrentContext
 * Signature: ()Lorg/lwjgl/openal/ALCcontext;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_openal_ALC_alcGetCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    alcGetContextsDevice
 * Signature: (J)Lorg/lwjgl/openal/ALCdevice;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_openal_ALC_alcGetContextsDevice
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    nalcSuspendContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_ALC_nalcSuspendContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    alcDestroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_openal_ALC_alcDestroyContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    nalcGetError
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_openal_ALC_nalcGetError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    nalcIsExtensionPresent
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_openal_ALC_nalcIsExtensionPresent
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_lwjgl_openal_ALC
 * Method:    nalcGetEnumValue
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_openal_ALC_nalcGetEnumValue
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
