/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_Win32PbufferPeerInfo */

#ifndef _Included_org_lwjgl_opengl_Win32PbufferPeerInfo
#define _Included_org_lwjgl_opengl_Win32PbufferPeerInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_Win32PbufferPeerInfo
 * Method:    nCreate
 * Signature: (Ljava/nio/ByteBuffer;IILorg/lwjgl/opengl/PixelFormat;Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32PbufferPeerInfo_nCreate
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32PbufferPeerInfo
 * Method:    nIsBufferLost
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_Win32PbufferPeerInfo_nIsBufferLost
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32PbufferPeerInfo
 * Method:    nSetPbufferAttrib
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32PbufferPeerInfo_nSetPbufferAttrib
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_Win32PbufferPeerInfo
 * Method:    nBindTexImageToPbuffer
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32PbufferPeerInfo_nBindTexImageToPbuffer
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_Win32PbufferPeerInfo
 * Method:    nReleaseTexImageFromPbuffer
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32PbufferPeerInfo_nReleaseTexImageFromPbuffer
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_Win32PbufferPeerInfo
 * Method:    nDestroy
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32PbufferPeerInfo_nDestroy
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
