/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_Win32DisplayPeerInfo */

#ifndef _Included_org_lwjgl_opengl_Win32DisplayPeerInfo
#define _Included_org_lwjgl_opengl_Win32DisplayPeerInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_Win32DisplayPeerInfo
 * Method:    createDummyDC
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32DisplayPeerInfo_createDummyDC
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32DisplayPeerInfo
 * Method:    nInitDC
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32DisplayPeerInfo_nInitDC
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32DisplayPeerInfo
 * Method:    nDestroy
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32DisplayPeerInfo_nDestroy
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32DisplayPeerInfo
 * Method:    setPixelFormat
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32DisplayPeerInfo_setPixelFormat
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
