/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_NativeSysImplementation */

#ifndef _Included_org_lwjgl_NativeSysImplementation
#define _Included_org_lwjgl_NativeSysImplementation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_NativeSysImplementation
 * Method:    getTimerResolution
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_NativeSysImplementation_getTimerResolution
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_NativeSysImplementation
 * Method:    getTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_NativeSysImplementation_getTime
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_NativeSysImplementation
 * Method:    alert
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_NativeSysImplementation_alert
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_lwjgl_NativeSysImplementation
 * Method:    openURL
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_NativeSysImplementation_openURL
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_lwjgl_NativeSysImplementation
 * Method:    getClipboard
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_NativeSysImplementation_getClipboard
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
