/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_Win32Display */

#ifndef _Included_org_lwjgl_opengl_Win32Display
#define _Included_org_lwjgl_opengl_Win32Display
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: peer_info */
/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    nCreateWindow
 * Signature: (Lorg/lwjgl/opengl/DisplayMode;ZII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_nCreateWindow
  (JNIEnv *, jobject, jobject, jboolean, jint, jint);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    destroyWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_destroyWindow
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    switchDisplayMode
 * Signature: (Lorg/lwjgl/opengl/DisplayMode;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_switchDisplayMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    resetDisplayMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_resetDisplayMode
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    getGammaRampLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_Win32Display_getGammaRampLength
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    setGammaRamp
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_setGammaRamp
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    getAdapter
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_opengl_Win32Display_getAdapter
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_opengl_Win32Display_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    init
 * Signature: ()Lorg/lwjgl/opengl/DisplayMode;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_Win32Display_init
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    setTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_setTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    isCloseRequested
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_Win32Display_isCloseRequested
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    isVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_Win32Display_isVisible
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    isActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_Win32Display_isActive
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    isDirty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_Win32Display_isDirty
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    nUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_nUpdate
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    didMaximize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_Win32Display_didMaximize
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    reshape
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_reshape
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    getAvailableDisplayModes
 * Signature: ()[Lorg/lwjgl/opengl/DisplayMode;
 */
JNIEXPORT jobjectArray JNICALL Java_org_lwjgl_opengl_Win32Display_getAvailableDisplayModes
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    hasWheel
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_opengl_Win32Display_hasWheel
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    getButtonCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_Win32Display_getButtonCount
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    createMouse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_createMouse
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    destroyMouse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_destroyMouse
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    pollMouse
 * Signature: (Ljava/nio/IntBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_pollMouse
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    readMouse
 * Signature: (Ljava/nio/IntBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_Win32Display_readMouse
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    grabMouse
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_grabMouse
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    setCursorPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_setCursorPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    setNativeCursor
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_setNativeCursor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    getMinCursorSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_Win32Display_getMinCursorSize
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    getMaxCursorSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_Win32Display_getMaxCursorSize
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    createKeyboard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_createKeyboard
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    destroyKeyboard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_destroyKeyboard
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    pollKeyboard
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_pollKeyboard
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    readKeyboard
 * Signature: (Ljava/nio/IntBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_Win32Display_readKeyboard
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    isStateKeySet
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_Win32Display_isStateKeySet
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    nCreateCursor
 * Signature: (IIIIILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_Win32Display_nCreateCursor
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    destroyCursor
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32Display_destroyCursor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_Win32Display
 * Method:    nGetPbufferCapabilities
 * Signature: (Lorg/lwjgl/opengl/PixelFormat;)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_Win32Display_nGetPbufferCapabilities
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
