/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_Win32PeerInfo */

#ifndef _Included_org_lwjgl_opengl_Win32PeerInfo
#define _Included_org_lwjgl_opengl_Win32PeerInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_opengl_Win32PeerInfo
 * Method:    createHandle
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_Win32PeerInfo_createHandle
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_Win32PeerInfo
 * Method:    nChoosePixelFormat
 * Signature: (Ljava/nio/ByteBuffer;IILorg/lwjgl/opengl/PixelFormat;Ljava/nio/IntBuffer;ZZZZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_Win32PeerInfo_nChoosePixelFormat
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jobject, jboolean, jboolean, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
