/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_MacOSXDisplay */

#ifndef _Included_org_lwjgl_opengl_MacOSXDisplay
#define _Included_org_lwjgl_opengl_MacOSXDisplay
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _00024assertionsDisabled */
#undef org_lwjgl_opengl_MacOSXDisplay_PBUFFER_HANDLE_SIZE
#define org_lwjgl_opengl_MacOSXDisplay_PBUFFER_HANDLE_SIZE 24L
#undef org_lwjgl_opengl_MacOSXDisplay_GAMMA_LENGTH
#define org_lwjgl_opengl_MacOSXDisplay_GAMMA_LENGTH 256L
/* Inaccessible static: class_00024org_00024lwjgl_00024opengl_00024MacOSXDisplay */
/*
 * Class:     org_lwjgl_opengl_MacOSXDisplay
 * Method:    setGammaRamp
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_MacOSXDisplay_setGammaRamp
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_MacOSXDisplay
 * Method:    restoreGamma
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_MacOSXDisplay_restoreGamma
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_MacOSXDisplay
 * Method:    nHideUI
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_MacOSXDisplay_nHideUI
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_lwjgl_opengl_MacOSXDisplay
 * Method:    getMouseDeltas
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_MacOSXDisplay_getMouseDeltas
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_MacOSXDisplay
 * Method:    updateContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_MacOSXDisplay_updateContext
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_MacOSXDisplay
 * Method:    nWarpCursor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_MacOSXDisplay_nWarpCursor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_opengl_MacOSXDisplay
 * Method:    nGrabMouse
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_MacOSXDisplay_nGrabMouse
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
