/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_audio_StreamPlaylist */

#ifndef _Included_org_lwjgl_audio_StreamPlaylist
#define _Included_org_lwjgl_audio_StreamPlaylist
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: working_mem */
#ifdef __cplusplus
}
#endif
#endif
