/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_audio_vorbis_DataStream */

#ifndef _Included_org_lwjgl_audio_vorbis_DataStream
#define _Included_org_lwjgl_audio_vorbis_DataStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lwjgl_audio_vorbis_DataStream
 * Method:    createALBuffer
 * Signature: (II)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_audio_vorbis_DataStream_createALBuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_lwjgl_audio_vorbis_DataStream
 * Method:    fillALBuffer
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_audio_vorbis_DataStream_fillALBuffer__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_lwjgl_audio_vorbis_DataStream
 * Method:    fillALBuffer
 * Signature: (IIILjava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_audio_vorbis_DataStream_fillALBuffer__IIILjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     org_lwjgl_audio_vorbis_DataStream
 * Method:    rewind
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_audio_vorbis_DataStream_rewind
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_audio_vorbis_DataStream
 * Method:    C_FillStreamInfo
 * Signature: (Lorg/lwjgl/audio/StreamInfo;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_audio_vorbis_DataStream_C_1FillStreamInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lwjgl_audio_vorbis_DataStream
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_audio_vorbis_DataStream_finalize
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_audio_vorbis_DataStream
 * Method:    tellTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_audio_vorbis_DataStream_tellTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
