version: 2
defaults: &defaults
  docker:
    - image: ubuntu:18.04
jobs:
  build_linux:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Id
          command: cat /etc/*release
      - run:
          name: Setup requirements
          command: apt-get update && apt-get install -y git ant
      - run:
          name: Build for Linux
          command: cd game && ant 
      - store_artifacts:
          path: game.jar
  build_win32:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Prepare the Windows build environment
          command: |
            export DISPLAY=xserver:0
            dpkg --add-architecture i386 
            apt-get update 
            apt-get install -y mingw-w64 mingw-w64-tools default-jdk libsaxonb-java curl ant git wine-stable procps xvfb osslsigncode wine32 
      - run:
          name: Build for Windows
          command: |
            cd game && ant
      - run:
          name: build starter files
          command: | 
            cd game/starter/exe/bolzplatz2006/ && make && cp bolzplatz.exe ../../../tools/setup/v1.0-windows/other/de/
            cd ../settings && make
            cd ../stadioneditor && make
            cd ../teameditor && make
      - run:
          name: start Inno Setup
          command: cd tools/setup/v1.0-windows && wine ISCC.exe bolzplatz2006-install.iss
      - store_artifacts:
          path: game.jar

workflows:
  version: 2
  build_all:
    jobs:
      - build_win32
