version: 2
defaults: &defaults
  docker:
    - image: ubuntu:18.04
jobs:
  build_linux:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Id
          command: cat /etc/*release
      - run:
          name: Setup requirements
          command: apt-get update && apt-get install -y git ant
      - run:
          name: Build for Linux
          command: cd game && ant 
      - store_artifacts:
          path: game.jar
  build_win32:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Prepare the Windows build environment
          command: |
            export DISPLAY=xserver:0
            dpkg --add-architecture i386 
            apt-get update 
            apt-get install -y mingw-w64 mingw-w64-tools default-jdk libsaxonb-java curl ant git wine-stable procps xvfb osslsigncode wine32
            curl -SL "https://files.jrsoftware.org/is/6/innosetup-6.1.2.exe" -o is.exe
            wine is.exe /SP- /VERYSILENT /ALLUSERS /SUPPRESSMSGBOXES
            rm is.exe
            cd "$HOME/.wine/drive_c/Program Files/Inno Setup 6/Languages"
            curl -L "https://api.github.com/repos/jrsoftware/issrc/tarball/is-6_1_2"
            tar xz --strip-components=4 --wildcards "*/Files/Languages/Unofficial/*.isl"
      - run:
          name: Build for Windows
          command: |
            cd game && ant
      - run:
          name: build starter files
          command: | 
            cd game/starter/exe/bolzplatz2006/ && make
            cd ../settings && make
            cd ../stadioneditor && make
            cd ../teameditor && make
      - store_artifacts:
          path: game.jar

workflows:
  version: 2
  build_all:
    jobs:
      - build_linux
      - build_win32
