/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_fmod3_FMOD */

#ifndef _Included_org_lwjgl_fmod3_FMOD
#define _Included_org_lwjgl_fmod3_FMOD
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: callbacks */
/* Inaccessible static: fmodClearUnit */
/* Inaccessible static: fmodClipAndCopyUnit */
/* Inaccessible static: fmodMusicUnit */
/* Inaccessible static: fmodSFXUnit */
/* Inaccessible static: fmodFFTUnit */
/* Inaccessible static: fmodFFTBuffer */
#undef org_lwjgl_fmod3_FMOD_FMUSIC_INSTCALLBACK
#define org_lwjgl_fmod3_FMOD_FMUSIC_INSTCALLBACK 0L
#undef org_lwjgl_fmod3_FMOD_FMUSIC_ORDERCALLBACK
#define org_lwjgl_fmod3_FMOD_FMUSIC_ORDERCALLBACK 1L
#undef org_lwjgl_fmod3_FMOD_FMUSIC_ROWCALLBACK
#define org_lwjgl_fmod3_FMOD_FMUSIC_ROWCALLBACK 2L
#undef org_lwjgl_fmod3_FMOD_FMUSIC_ZXXCALLBACK
#define org_lwjgl_fmod3_FMOD_FMUSIC_ZXXCALLBACK 3L
#undef org_lwjgl_fmod3_FMOD_FSOUND_DSPCALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_DSPCALLBACK 4L
#undef org_lwjgl_fmod3_FMOD_FSOUND_STREAMCALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_STREAMCALLBACK 5L
#undef org_lwjgl_fmod3_FMOD_FSOUND_ALLOCCALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_ALLOCCALLBACK 6L
#undef org_lwjgl_fmod3_FMOD_FSOUND_REALLOCCALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_REALLOCCALLBACK 7L
#undef org_lwjgl_fmod3_FMOD_FSOUND_FREECALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_FREECALLBACK 8L
#undef org_lwjgl_fmod3_FMOD_FSOUND_OPENCALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_OPENCALLBACK 9L
#undef org_lwjgl_fmod3_FMOD_FSOUND_CLOSECALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_CLOSECALLBACK 10L
#undef org_lwjgl_fmod3_FMOD_FSOUND_METADATACALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_METADATACALLBACK 11L
#undef org_lwjgl_fmod3_FMOD_FSOUND_READCALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_READCALLBACK 12L
#undef org_lwjgl_fmod3_FMOD_FSOUND_SEEKCALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_SEEKCALLBACK 13L
#undef org_lwjgl_fmod3_FMOD_FSOUND_TELLCALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_TELLCALLBACK 14L
#undef org_lwjgl_fmod3_FMOD_FSOUND_ENDCALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_ENDCALLBACK 15L
#undef org_lwjgl_fmod3_FMOD_FSOUND_SYNCCALLBACK
#define org_lwjgl_fmod3_FMOD_FSOUND_SYNCCALLBACK 16L
/* Inaccessible static: created */
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_NONE
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_NONE 0L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_BUSY
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_BUSY 1L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_UNINITIALIZED
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_UNINITIALIZED 2L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_INIT
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_INIT 3L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_ALLOCATED
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_ALLOCATED 4L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_PLAY
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_PLAY 5L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_OUTPUT_FORMAT
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_OUTPUT_FORMAT 6L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_COOPERATIVELEVEL
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_COOPERATIVELEVEL 7L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_CREATEBUFFER
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_CREATEBUFFER 8L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_FILE_NOTFOUND
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_FILE_NOTFOUND 9L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_FILE_FORMAT
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_FILE_FORMAT 10L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_FILE_BAD
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_FILE_BAD 11L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_MEMORY
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_MEMORY 12L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_VERSION
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_VERSION 13L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_INVALID_PARAM
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_INVALID_PARAM 14L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_NO_EAX
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_NO_EAX 15L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_CHANNEL_ALLOC
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_CHANNEL_ALLOC 17L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_RECORD
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_RECORD 18L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_MEDIAPLAYER
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_MEDIAPLAYER 19L
#undef org_lwjgl_fmod3_FMOD_FMOD_ERR_CDDEVICE
#define org_lwjgl_fmod3_FMOD_FMOD_ERR_CDDEVICE 20L
/* Inaccessible static: initialized */
/* Inaccessible static: JNI_LIBRARY_NAME */
/* Inaccessible static: FMOD_WIN32_LIBRARY_NAME */
/* Inaccessible static: FMOD_LINUX_LIBRARY_NAME */
/* Inaccessible static: FMOD_OSX_LIBRARY_NAME */
/* Inaccessible static: class_00024org_00024lwjgl_00024fmod3_00024FMOD */
/* Inaccessible static: class_00024java_00024lang_00024String */
/*
 * Class:     org_lwjgl_fmod3_FMOD
 * Method:    getNativeLibraryVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_fmod3_FMOD_getNativeLibraryVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_fmod3_FMOD
 * Method:    nCreate
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_fmod3_FMOD_nCreate
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_lwjgl_fmod3_FMOD
 * Method:    nDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_fmod3_FMOD_nDestroy
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_fmod3_FMOD
 * Method:    FMOD_ErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_fmod3_FMOD_FMOD_1ErrorString
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
