/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_devil_IL */

#ifndef _Included_org_lwjgl_devil_IL
#define _Included_org_lwjgl_devil_IL
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_devil_IL_IL_FALSE
#define org_lwjgl_devil_IL_IL_FALSE 0L
#undef org_lwjgl_devil_IL_IL_TRUE
#define org_lwjgl_devil_IL_IL_TRUE 1L
#undef org_lwjgl_devil_IL_IL_COLOUR_INDEX
#define org_lwjgl_devil_IL_IL_COLOUR_INDEX 6400L
#undef org_lwjgl_devil_IL_IL_COLOR_INDEX
#define org_lwjgl_devil_IL_IL_COLOR_INDEX 6400L
#undef org_lwjgl_devil_IL_IL_RGB
#define org_lwjgl_devil_IL_IL_RGB 6407L
#undef org_lwjgl_devil_IL_IL_RGBA
#define org_lwjgl_devil_IL_IL_RGBA 6408L
#undef org_lwjgl_devil_IL_IL_BGR
#define org_lwjgl_devil_IL_IL_BGR 32992L
#undef org_lwjgl_devil_IL_IL_BGRA
#define org_lwjgl_devil_IL_IL_BGRA 32993L
#undef org_lwjgl_devil_IL_IL_LUMINANCE
#define org_lwjgl_devil_IL_IL_LUMINANCE 6409L
#undef org_lwjgl_devil_IL_IL_BYTE
#define org_lwjgl_devil_IL_IL_BYTE 5120L
#undef org_lwjgl_devil_IL_IL_UNSIGNED_BYTE
#define org_lwjgl_devil_IL_IL_UNSIGNED_BYTE 5121L
#undef org_lwjgl_devil_IL_IL_SHORT
#define org_lwjgl_devil_IL_IL_SHORT 5122L
#undef org_lwjgl_devil_IL_IL_UNSIGNED_SHORT
#define org_lwjgl_devil_IL_IL_UNSIGNED_SHORT 5123L
#undef org_lwjgl_devil_IL_IL_INT
#define org_lwjgl_devil_IL_IL_INT 5124L
#undef org_lwjgl_devil_IL_IL_UNSIGNED_INT
#define org_lwjgl_devil_IL_IL_UNSIGNED_INT 5125L
#undef org_lwjgl_devil_IL_IL_FLOAT
#define org_lwjgl_devil_IL_IL_FLOAT 5126L
#undef org_lwjgl_devil_IL_IL_DOUBLE
#define org_lwjgl_devil_IL_IL_DOUBLE 5130L
#undef org_lwjgl_devil_IL_IL_VENDOR
#define org_lwjgl_devil_IL_IL_VENDOR 7936L
#undef org_lwjgl_devil_IL_IL_LOAD_EXT
#define org_lwjgl_devil_IL_IL_LOAD_EXT 7937L
#undef org_lwjgl_devil_IL_IL_SAVE_EXT
#define org_lwjgl_devil_IL_IL_SAVE_EXT 7938L
#undef org_lwjgl_devil_IL_IL_ORIGIN_BIT
#define org_lwjgl_devil_IL_IL_ORIGIN_BIT 1L
#undef org_lwjgl_devil_IL_IL_FILE_BIT
#define org_lwjgl_devil_IL_IL_FILE_BIT 2L
#undef org_lwjgl_devil_IL_IL_PAL_BIT
#define org_lwjgl_devil_IL_IL_PAL_BIT 4L
#undef org_lwjgl_devil_IL_IL_FORMAT_BIT
#define org_lwjgl_devil_IL_IL_FORMAT_BIT 8L
#undef org_lwjgl_devil_IL_IL_TYPE_BIT
#define org_lwjgl_devil_IL_IL_TYPE_BIT 16L
#undef org_lwjgl_devil_IL_IL_COMPRESS_BIT
#define org_lwjgl_devil_IL_IL_COMPRESS_BIT 32L
#undef org_lwjgl_devil_IL_IL_LOADFAIL_BIT
#define org_lwjgl_devil_IL_IL_LOADFAIL_BIT 64L
#undef org_lwjgl_devil_IL_IL_FORMAT_SPECIFIC_BIT
#define org_lwjgl_devil_IL_IL_FORMAT_SPECIFIC_BIT 128L
#undef org_lwjgl_devil_IL_IL_ALL_ATTRIB_BITS
#define org_lwjgl_devil_IL_IL_ALL_ATTRIB_BITS 1048575L
#undef org_lwjgl_devil_IL_IL_PAL_NONE
#define org_lwjgl_devil_IL_IL_PAL_NONE 1024L
#undef org_lwjgl_devil_IL_IL_PAL_RGB24
#define org_lwjgl_devil_IL_IL_PAL_RGB24 1025L
#undef org_lwjgl_devil_IL_IL_PAL_RGB32
#define org_lwjgl_devil_IL_IL_PAL_RGB32 1026L
#undef org_lwjgl_devil_IL_IL_PAL_RGBA32
#define org_lwjgl_devil_IL_IL_PAL_RGBA32 1027L
#undef org_lwjgl_devil_IL_IL_PAL_BGR24
#define org_lwjgl_devil_IL_IL_PAL_BGR24 1028L
#undef org_lwjgl_devil_IL_IL_PAL_BGR32
#define org_lwjgl_devil_IL_IL_PAL_BGR32 1029L
#undef org_lwjgl_devil_IL_IL_PAL_BGRA32
#define org_lwjgl_devil_IL_IL_PAL_BGRA32 1030L
#undef org_lwjgl_devil_IL_IL_TYPE_UNKNOWN
#define org_lwjgl_devil_IL_IL_TYPE_UNKNOWN 0L
#undef org_lwjgl_devil_IL_IL_BMP
#define org_lwjgl_devil_IL_IL_BMP 1056L
#undef org_lwjgl_devil_IL_IL_CUT
#define org_lwjgl_devil_IL_IL_CUT 1057L
#undef org_lwjgl_devil_IL_IL_DOOM
#define org_lwjgl_devil_IL_IL_DOOM 1058L
#undef org_lwjgl_devil_IL_IL_DOOM_FLAT
#define org_lwjgl_devil_IL_IL_DOOM_FLAT 1059L
#undef org_lwjgl_devil_IL_IL_ICO
#define org_lwjgl_devil_IL_IL_ICO 1060L
#undef org_lwjgl_devil_IL_IL_JPG
#define org_lwjgl_devil_IL_IL_JPG 1061L
#undef org_lwjgl_devil_IL_IL_LBM
#define org_lwjgl_devil_IL_IL_LBM 1062L
#undef org_lwjgl_devil_IL_IL_PCD
#define org_lwjgl_devil_IL_IL_PCD 1063L
#undef org_lwjgl_devil_IL_IL_PCX
#define org_lwjgl_devil_IL_IL_PCX 1064L
#undef org_lwjgl_devil_IL_IL_PIC
#define org_lwjgl_devil_IL_IL_PIC 1065L
#undef org_lwjgl_devil_IL_IL_PNG
#define org_lwjgl_devil_IL_IL_PNG 1066L
#undef org_lwjgl_devil_IL_IL_PNM
#define org_lwjgl_devil_IL_IL_PNM 1067L
#undef org_lwjgl_devil_IL_IL_SGI
#define org_lwjgl_devil_IL_IL_SGI 1068L
#undef org_lwjgl_devil_IL_IL_TGA
#define org_lwjgl_devil_IL_IL_TGA 1069L
#undef org_lwjgl_devil_IL_IL_TIF
#define org_lwjgl_devil_IL_IL_TIF 1070L
#undef org_lwjgl_devil_IL_IL_CHEAD
#define org_lwjgl_devil_IL_IL_CHEAD 1071L
#undef org_lwjgl_devil_IL_IL_RAW
#define org_lwjgl_devil_IL_IL_RAW 1072L
#undef org_lwjgl_devil_IL_IL_MDL
#define org_lwjgl_devil_IL_IL_MDL 1073L
#undef org_lwjgl_devil_IL_IL_WAL
#define org_lwjgl_devil_IL_IL_WAL 1074L
#undef org_lwjgl_devil_IL_IL_OIL
#define org_lwjgl_devil_IL_IL_OIL 1075L
#undef org_lwjgl_devil_IL_IL_LIF
#define org_lwjgl_devil_IL_IL_LIF 1076L
#undef org_lwjgl_devil_IL_IL_MNG
#define org_lwjgl_devil_IL_IL_MNG 1077L
#undef org_lwjgl_devil_IL_IL_JNG
#define org_lwjgl_devil_IL_IL_JNG 1077L
#undef org_lwjgl_devil_IL_IL_GIF
#define org_lwjgl_devil_IL_IL_GIF 1078L
#undef org_lwjgl_devil_IL_IL_DDS
#define org_lwjgl_devil_IL_IL_DDS 1079L
#undef org_lwjgl_devil_IL_IL_DCX
#define org_lwjgl_devil_IL_IL_DCX 1080L
#undef org_lwjgl_devil_IL_IL_PSD
#define org_lwjgl_devil_IL_IL_PSD 1081L
#undef org_lwjgl_devil_IL_IL_EXIF
#define org_lwjgl_devil_IL_IL_EXIF 1082L
#undef org_lwjgl_devil_IL_IL_PSP
#define org_lwjgl_devil_IL_IL_PSP 1083L
#undef org_lwjgl_devil_IL_IL_PIX
#define org_lwjgl_devil_IL_IL_PIX 1084L
#undef org_lwjgl_devil_IL_IL_PXR
#define org_lwjgl_devil_IL_IL_PXR 1085L
#undef org_lwjgl_devil_IL_IL_XPM
#define org_lwjgl_devil_IL_IL_XPM 1086L
#undef org_lwjgl_devil_IL_IL_JASC_PAL
#define org_lwjgl_devil_IL_IL_JASC_PAL 1141L
#undef org_lwjgl_devil_IL_IL_NO_ERROR
#define org_lwjgl_devil_IL_IL_NO_ERROR 0L
#undef org_lwjgl_devil_IL_IL_INVALID_ENUM
#define org_lwjgl_devil_IL_IL_INVALID_ENUM 1281L
#undef org_lwjgl_devil_IL_IL_OUT_OF_MEMORY
#define org_lwjgl_devil_IL_IL_OUT_OF_MEMORY 1282L
#undef org_lwjgl_devil_IL_IL_FORMAT_NOT_SUPPORTED
#define org_lwjgl_devil_IL_IL_FORMAT_NOT_SUPPORTED 1283L
#undef org_lwjgl_devil_IL_IL_INTERNAL_ERROR
#define org_lwjgl_devil_IL_IL_INTERNAL_ERROR 1284L
#undef org_lwjgl_devil_IL_IL_INVALID_VALUE
#define org_lwjgl_devil_IL_IL_INVALID_VALUE 1285L
#undef org_lwjgl_devil_IL_IL_ILLEGAL_OPERATION
#define org_lwjgl_devil_IL_IL_ILLEGAL_OPERATION 1286L
#undef org_lwjgl_devil_IL_IL_ILLEGAL_FILE_VALUE
#define org_lwjgl_devil_IL_IL_ILLEGAL_FILE_VALUE 1287L
#undef org_lwjgl_devil_IL_IL_INVALID_FILE_HEADER
#define org_lwjgl_devil_IL_IL_INVALID_FILE_HEADER 1288L
#undef org_lwjgl_devil_IL_IL_INVALID_PARAM
#define org_lwjgl_devil_IL_IL_INVALID_PARAM 1289L
#undef org_lwjgl_devil_IL_IL_COULD_NOT_OPEN_FILE
#define org_lwjgl_devil_IL_IL_COULD_NOT_OPEN_FILE 1290L
#undef org_lwjgl_devil_IL_IL_INVALID_EXTENSION
#define org_lwjgl_devil_IL_IL_INVALID_EXTENSION 1291L
#undef org_lwjgl_devil_IL_IL_FILE_ALREADY_EXISTS
#define org_lwjgl_devil_IL_IL_FILE_ALREADY_EXISTS 1292L
#undef org_lwjgl_devil_IL_IL_OUT_FORMAT_SAME
#define org_lwjgl_devil_IL_IL_OUT_FORMAT_SAME 1293L
#undef org_lwjgl_devil_IL_IL_STACK_OVERFLOW
#define org_lwjgl_devil_IL_IL_STACK_OVERFLOW 1294L
#undef org_lwjgl_devil_IL_IL_STACK_UNDERFLOW
#define org_lwjgl_devil_IL_IL_STACK_UNDERFLOW 1295L
#undef org_lwjgl_devil_IL_IL_INVALID_CONVERSION
#define org_lwjgl_devil_IL_IL_INVALID_CONVERSION 1296L
#undef org_lwjgl_devil_IL_IL_BAD_DIMENSIONS
#define org_lwjgl_devil_IL_IL_BAD_DIMENSIONS 1297L
#undef org_lwjgl_devil_IL_IL_FILE_READ_ERROR
#define org_lwjgl_devil_IL_IL_FILE_READ_ERROR 1298L
#undef org_lwjgl_devil_IL_IL_LIB_GIF_ERROR
#define org_lwjgl_devil_IL_IL_LIB_GIF_ERROR 1505L
#undef org_lwjgl_devil_IL_IL_LIB_JPEG_ERROR
#define org_lwjgl_devil_IL_IL_LIB_JPEG_ERROR 1506L
#undef org_lwjgl_devil_IL_IL_LIB_PNG_ERROR
#define org_lwjgl_devil_IL_IL_LIB_PNG_ERROR 1507L
#undef org_lwjgl_devil_IL_IL_LIB_TIFF_ERROR
#define org_lwjgl_devil_IL_IL_LIB_TIFF_ERROR 1508L
#undef org_lwjgl_devil_IL_IL_LIB_MNG_ERROR
#define org_lwjgl_devil_IL_IL_LIB_MNG_ERROR 1509L
#undef org_lwjgl_devil_IL_IL_UNKNOWN_ERROR
#define org_lwjgl_devil_IL_IL_UNKNOWN_ERROR 1535L
#undef org_lwjgl_devil_IL_IL_ORIGIN_SET
#define org_lwjgl_devil_IL_IL_ORIGIN_SET 1536L
#undef org_lwjgl_devil_IL_IL_ORIGIN_LOWER_LEFT
#define org_lwjgl_devil_IL_IL_ORIGIN_LOWER_LEFT 1537L
#undef org_lwjgl_devil_IL_IL_ORIGIN_UPPER_LEFT
#define org_lwjgl_devil_IL_IL_ORIGIN_UPPER_LEFT 1538L
#undef org_lwjgl_devil_IL_IL_ORIGIN_MODE
#define org_lwjgl_devil_IL_IL_ORIGIN_MODE 1539L
#undef org_lwjgl_devil_IL_IL_FORMAT_SET
#define org_lwjgl_devil_IL_IL_FORMAT_SET 1552L
#undef org_lwjgl_devil_IL_IL_FORMAT_MODE
#define org_lwjgl_devil_IL_IL_FORMAT_MODE 1553L
#undef org_lwjgl_devil_IL_IL_TYPE_SET
#define org_lwjgl_devil_IL_IL_TYPE_SET 1554L
#undef org_lwjgl_devil_IL_IL_TYPE_MODE
#define org_lwjgl_devil_IL_IL_TYPE_MODE 1555L
#undef org_lwjgl_devil_IL_IL_FILE_OVERWRITE
#define org_lwjgl_devil_IL_IL_FILE_OVERWRITE 1568L
#undef org_lwjgl_devil_IL_IL_FILE_MODE
#define org_lwjgl_devil_IL_IL_FILE_MODE 1569L
#undef org_lwjgl_devil_IL_IL_CONV_PAL
#define org_lwjgl_devil_IL_IL_CONV_PAL 1584L
#undef org_lwjgl_devil_IL_IL_DEFAULT_ON_FAIL
#define org_lwjgl_devil_IL_IL_DEFAULT_ON_FAIL 1586L
#undef org_lwjgl_devil_IL_IL_USE_KEY_COLOUR
#define org_lwjgl_devil_IL_IL_USE_KEY_COLOUR 1589L
#undef org_lwjgl_devil_IL_IL_USE_KEY_COLOR
#define org_lwjgl_devil_IL_IL_USE_KEY_COLOR 1589L
#undef org_lwjgl_devil_IL_IL_SAVE_INTERLACED
#define org_lwjgl_devil_IL_IL_SAVE_INTERLACED 1593L
#undef org_lwjgl_devil_IL_IL_INTERLACE_MODE
#define org_lwjgl_devil_IL_IL_INTERLACE_MODE 1594L
#undef org_lwjgl_devil_IL_IL_QUANTIZATION_MODE
#define org_lwjgl_devil_IL_IL_QUANTIZATION_MODE 1600L
#undef org_lwjgl_devil_IL_IL_WU_QUANT
#define org_lwjgl_devil_IL_IL_WU_QUANT 1601L
#undef org_lwjgl_devil_IL_IL_NEU_QUANT
#define org_lwjgl_devil_IL_IL_NEU_QUANT 1602L
#undef org_lwjgl_devil_IL_IL_NEU_QUANT_SAMPLE
#define org_lwjgl_devil_IL_IL_NEU_QUANT_SAMPLE 1603L
#undef org_lwjgl_devil_IL_IL_FASTEST
#define org_lwjgl_devil_IL_IL_FASTEST 1632L
#undef org_lwjgl_devil_IL_IL_LESS_MEM
#define org_lwjgl_devil_IL_IL_LESS_MEM 1633L
#undef org_lwjgl_devil_IL_IL_DONT_CARE
#define org_lwjgl_devil_IL_IL_DONT_CARE 1634L
#undef org_lwjgl_devil_IL_IL_MEM_SPEED_HINT
#define org_lwjgl_devil_IL_IL_MEM_SPEED_HINT 1637L
#undef org_lwjgl_devil_IL_IL_USE_COMPRESSION
#define org_lwjgl_devil_IL_IL_USE_COMPRESSION 1638L
#undef org_lwjgl_devil_IL_IL_NO_COMPRESSION
#define org_lwjgl_devil_IL_IL_NO_COMPRESSION 1639L
#undef org_lwjgl_devil_IL_IL_COMPRESSION_HINT
#define org_lwjgl_devil_IL_IL_COMPRESSION_HINT 1640L
#undef org_lwjgl_devil_IL_IL_SUB_NEXT
#define org_lwjgl_devil_IL_IL_SUB_NEXT 1664L
#undef org_lwjgl_devil_IL_IL_SUB_MIPMAP
#define org_lwjgl_devil_IL_IL_SUB_MIPMAP 1665L
#undef org_lwjgl_devil_IL_IL_SUB_LAYER
#define org_lwjgl_devil_IL_IL_SUB_LAYER 1666L
#undef org_lwjgl_devil_IL_IL_COMPRESS_MODE
#define org_lwjgl_devil_IL_IL_COMPRESS_MODE 1792L
#undef org_lwjgl_devil_IL_IL_COMPRESS_NONE
#define org_lwjgl_devil_IL_IL_COMPRESS_NONE 1793L
#undef org_lwjgl_devil_IL_IL_COMPRESS_RLE
#define org_lwjgl_devil_IL_IL_COMPRESS_RLE 1794L
#undef org_lwjgl_devil_IL_IL_COMPRESS_LZO
#define org_lwjgl_devil_IL_IL_COMPRESS_LZO 1795L
#undef org_lwjgl_devil_IL_IL_COMPRESS_ZLIB
#define org_lwjgl_devil_IL_IL_COMPRESS_ZLIB 1796L
#undef org_lwjgl_devil_IL_IL_TGA_CREATE_STAMP
#define org_lwjgl_devil_IL_IL_TGA_CREATE_STAMP 1808L
#undef org_lwjgl_devil_IL_IL_JPG_QUALITY
#define org_lwjgl_devil_IL_IL_JPG_QUALITY 1809L
#undef org_lwjgl_devil_IL_IL_PNG_INTERLACE
#define org_lwjgl_devil_IL_IL_PNG_INTERLACE 1810L
#undef org_lwjgl_devil_IL_IL_TGA_RLE
#define org_lwjgl_devil_IL_IL_TGA_RLE 1811L
#undef org_lwjgl_devil_IL_IL_BMP_RLE
#define org_lwjgl_devil_IL_IL_BMP_RLE 1812L
#undef org_lwjgl_devil_IL_IL_SGI_RLE
#define org_lwjgl_devil_IL_IL_SGI_RLE 1813L
#undef org_lwjgl_devil_IL_IL_TGA_ID_STRING
#define org_lwjgl_devil_IL_IL_TGA_ID_STRING 1815L
#undef org_lwjgl_devil_IL_IL_TGA_AUTHNAME_STRING
#define org_lwjgl_devil_IL_IL_TGA_AUTHNAME_STRING 1816L
#undef org_lwjgl_devil_IL_IL_TGA_AUTHCOMMENT_STRING
#define org_lwjgl_devil_IL_IL_TGA_AUTHCOMMENT_STRING 1817L
#undef org_lwjgl_devil_IL_IL_PNG_AUTHNAME_STRING
#define org_lwjgl_devil_IL_IL_PNG_AUTHNAME_STRING 1818L
#undef org_lwjgl_devil_IL_IL_PNG_TITLE_STRING
#define org_lwjgl_devil_IL_IL_PNG_TITLE_STRING 1819L
#undef org_lwjgl_devil_IL_IL_PNG_DESCRIPTION_STRING
#define org_lwjgl_devil_IL_IL_PNG_DESCRIPTION_STRING 1820L
#undef org_lwjgl_devil_IL_IL_TIF_DESCRIPTION_STRING
#define org_lwjgl_devil_IL_IL_TIF_DESCRIPTION_STRING 1821L
#undef org_lwjgl_devil_IL_IL_TIF_HOSTCOMPUTER_STRING
#define org_lwjgl_devil_IL_IL_TIF_HOSTCOMPUTER_STRING 1822L
#undef org_lwjgl_devil_IL_IL_TIF_DOCUMENTNAME_STRING
#define org_lwjgl_devil_IL_IL_TIF_DOCUMENTNAME_STRING 1823L
#undef org_lwjgl_devil_IL_IL_TIF_AUTHNAME_STRING
#define org_lwjgl_devil_IL_IL_TIF_AUTHNAME_STRING 1824L
#undef org_lwjgl_devil_IL_IL_JPG_SAVE_FORMAT
#define org_lwjgl_devil_IL_IL_JPG_SAVE_FORMAT 1825L
#undef org_lwjgl_devil_IL_IL_CHEAD_HEADER_STRING
#define org_lwjgl_devil_IL_IL_CHEAD_HEADER_STRING 1826L
#undef org_lwjgl_devil_IL_IL_PCD_PICNUM
#define org_lwjgl_devil_IL_IL_PCD_PICNUM 1827L
#undef org_lwjgl_devil_IL_IL_DXTC_FORMAT
#define org_lwjgl_devil_IL_IL_DXTC_FORMAT 1797L
#undef org_lwjgl_devil_IL_IL_DXT1
#define org_lwjgl_devil_IL_IL_DXT1 1798L
#undef org_lwjgl_devil_IL_IL_DXT2
#define org_lwjgl_devil_IL_IL_DXT2 1799L
#undef org_lwjgl_devil_IL_IL_DXT3
#define org_lwjgl_devil_IL_IL_DXT3 1800L
#undef org_lwjgl_devil_IL_IL_DXT4
#define org_lwjgl_devil_IL_IL_DXT4 1801L
#undef org_lwjgl_devil_IL_IL_DXT5
#define org_lwjgl_devil_IL_IL_DXT5 1802L
#undef org_lwjgl_devil_IL_IL_DXT_NO_COMP
#define org_lwjgl_devil_IL_IL_DXT_NO_COMP 1803L
#undef org_lwjgl_devil_IL_IL_KEEP_DXTC_DATA
#define org_lwjgl_devil_IL_IL_KEEP_DXTC_DATA 1804L
#undef org_lwjgl_devil_IL_IL_DXTC_DATA_FORMAT
#define org_lwjgl_devil_IL_IL_DXTC_DATA_FORMAT 1805L
#undef org_lwjgl_devil_IL_IL_CUBEMAP_POSITIVEX
#define org_lwjgl_devil_IL_IL_CUBEMAP_POSITIVEX 1024L
#undef org_lwjgl_devil_IL_IL_CUBEMAP_NEGATIVEX
#define org_lwjgl_devil_IL_IL_CUBEMAP_NEGATIVEX 2048L
#undef org_lwjgl_devil_IL_IL_CUBEMAP_POSITIVEY
#define org_lwjgl_devil_IL_IL_CUBEMAP_POSITIVEY 4096L
#undef org_lwjgl_devil_IL_IL_CUBEMAP_NEGATIVEY
#define org_lwjgl_devil_IL_IL_CUBEMAP_NEGATIVEY 8192L
#undef org_lwjgl_devil_IL_IL_CUBEMAP_POSITIVEZ
#define org_lwjgl_devil_IL_IL_CUBEMAP_POSITIVEZ 16384L
#undef org_lwjgl_devil_IL_IL_CUBEMAP_NEGATIVEZ
#define org_lwjgl_devil_IL_IL_CUBEMAP_NEGATIVEZ 32768L
#undef org_lwjgl_devil_IL_IL_VERSION_NUM
#define org_lwjgl_devil_IL_IL_VERSION_NUM 3554L
#undef org_lwjgl_devil_IL_IL_IMAGE_WIDTH
#define org_lwjgl_devil_IL_IL_IMAGE_WIDTH 3556L
#undef org_lwjgl_devil_IL_IL_IMAGE_HEIGHT
#define org_lwjgl_devil_IL_IL_IMAGE_HEIGHT 3557L
#undef org_lwjgl_devil_IL_IL_IMAGE_DEPTH
#define org_lwjgl_devil_IL_IL_IMAGE_DEPTH 3558L
#undef org_lwjgl_devil_IL_IL_IMAGE_SIZE_OF_DATA
#define org_lwjgl_devil_IL_IL_IMAGE_SIZE_OF_DATA 3559L
#undef org_lwjgl_devil_IL_IL_IMAGE_BPP
#define org_lwjgl_devil_IL_IL_IMAGE_BPP 3560L
#undef org_lwjgl_devil_IL_IL_IMAGE_BYTES_PER_PIXEL
#define org_lwjgl_devil_IL_IL_IMAGE_BYTES_PER_PIXEL 3560L
#undef org_lwjgl_devil_IL_IL_IMAGE_BITS_PER_PIXEL
#define org_lwjgl_devil_IL_IL_IMAGE_BITS_PER_PIXEL 3561L
#undef org_lwjgl_devil_IL_IL_IMAGE_FORMAT
#define org_lwjgl_devil_IL_IL_IMAGE_FORMAT 3562L
#undef org_lwjgl_devil_IL_IL_IMAGE_TYPE
#define org_lwjgl_devil_IL_IL_IMAGE_TYPE 3563L
#undef org_lwjgl_devil_IL_IL_PALETTE_TYPE
#define org_lwjgl_devil_IL_IL_PALETTE_TYPE 3564L
#undef org_lwjgl_devil_IL_IL_PALETTE_SIZE
#define org_lwjgl_devil_IL_IL_PALETTE_SIZE 3565L
#undef org_lwjgl_devil_IL_IL_PALETTE_BPP
#define org_lwjgl_devil_IL_IL_PALETTE_BPP 3566L
#undef org_lwjgl_devil_IL_IL_PALETTE_NUM_COLS
#define org_lwjgl_devil_IL_IL_PALETTE_NUM_COLS 3567L
#undef org_lwjgl_devil_IL_IL_PALETTE_BASE_TYPE
#define org_lwjgl_devil_IL_IL_PALETTE_BASE_TYPE 3568L
#undef org_lwjgl_devil_IL_IL_NUM_IMAGES
#define org_lwjgl_devil_IL_IL_NUM_IMAGES 3569L
#undef org_lwjgl_devil_IL_IL_NUM_MIPMAPS
#define org_lwjgl_devil_IL_IL_NUM_MIPMAPS 3570L
#undef org_lwjgl_devil_IL_IL_NUM_LAYERS
#define org_lwjgl_devil_IL_IL_NUM_LAYERS 3571L
#undef org_lwjgl_devil_IL_IL_ACTIVE_IMAGE
#define org_lwjgl_devil_IL_IL_ACTIVE_IMAGE 3572L
#undef org_lwjgl_devil_IL_IL_ACTIVE_MIPMAP
#define org_lwjgl_devil_IL_IL_ACTIVE_MIPMAP 3573L
#undef org_lwjgl_devil_IL_IL_ACTIVE_LAYER
#define org_lwjgl_devil_IL_IL_ACTIVE_LAYER 3574L
#undef org_lwjgl_devil_IL_IL_CUR_IMAGE
#define org_lwjgl_devil_IL_IL_CUR_IMAGE 3575L
#undef org_lwjgl_devil_IL_IL_IMAGE_DURATION
#define org_lwjgl_devil_IL_IL_IMAGE_DURATION 3576L
#undef org_lwjgl_devil_IL_IL_IMAGE_PLANESIZE
#define org_lwjgl_devil_IL_IL_IMAGE_PLANESIZE 3577L
#undef org_lwjgl_devil_IL_IL_IMAGE_BPC
#define org_lwjgl_devil_IL_IL_IMAGE_BPC 3578L
#undef org_lwjgl_devil_IL_IL_IMAGE_OFFX
#define org_lwjgl_devil_IL_IL_IMAGE_OFFX 3579L
#undef org_lwjgl_devil_IL_IL_IMAGE_OFFY
#define org_lwjgl_devil_IL_IL_IMAGE_OFFY 3580L
#undef org_lwjgl_devil_IL_IL_IMAGE_CUBEFLAGS
#define org_lwjgl_devil_IL_IL_IMAGE_CUBEFLAGS 3581L
#undef org_lwjgl_devil_IL_IL_SEEK_SET
#define org_lwjgl_devil_IL_IL_SEEK_SET 0L
#undef org_lwjgl_devil_IL_IL_SEEK_CUR
#define org_lwjgl_devil_IL_IL_SEEK_CUR 1L
#undef org_lwjgl_devil_IL_IL_SEEK_END
#define org_lwjgl_devil_IL_IL_SEEK_END 2L
#undef org_lwjgl_devil_IL_IL_EOF
#define org_lwjgl_devil_IL_IL_EOF -1L
/* Inaccessible static: created */
/* Inaccessible static: class_00024org_00024lwjgl_00024devil_00024IL */
/* Inaccessible static: class_00024org_00024lwjgl_00024devil_00024ILU */
/* Inaccessible static: class_00024org_00024lwjgl_00024devil_00024ILUT */
/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilActiveImage
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilActiveImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilActiveLayer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilActiveLayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilActiveMipmap
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilActiveMipmap
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilApplyPal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilApplyPal
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilApplyProfile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilApplyProfile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilBindImage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilBindImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilBlit
 * Signature: (IIIIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilBlit
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilClearColour
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilClearColour
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilClearImage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilClearImage
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilCloneCurImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_IL_ilCloneCurImage
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilCompressFunc
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilCompressFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilConvertImage
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilConvertImage
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilConvertPal
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilConvertPal
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilCopyImage
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilCopyImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilCopyPixels
 * Signature: (IIIIIIIILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_IL_nilCopyPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilCreateSubImage
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_IL_ilCreateSubImage
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilDefaultImage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilDefaultImage
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilDeleteImages
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_nilDeleteImages
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilDisable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilDisable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilEnable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilEnable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilFormatFunc
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilFormatFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilGenImages
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_nilGenImages
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilGetAlpha
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_devil_IL_ilGetAlpha
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilModAlpha
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilModAlpha
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilSetAlpha
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilSetAlpha
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilGetBoolean
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilGetBoolean
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilGetBooleanv
 * Signature: (ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_nilGetBooleanv
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilGetIntegerv
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_nilGetIntegerv
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilGetData
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_devil_IL_ilGetData
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_IL_ilGetError
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilGetInteger
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_IL_ilGetInteger
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilGetLumpPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_IL_ilGetLumpPos
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilGetPalette
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_devil_IL_ilGetPalette
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_devil_IL_ilGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilHint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilInit
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilIsDisabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilIsDisabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilIsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilIsEnabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilIsImage
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilIsImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilIsValid
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilIsValid
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilIsValidL
 * Signature: (ILjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_nilIsValidL
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilKeyColour
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilKeyColour
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilLoad
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilLoad
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilLoadImage
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilLoadImage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilLoadL
 * Signature: (ILjava/nio/ByteBuffer;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_nilLoadL
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilLoadPal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilLoadPal
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilOriginFunc
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilOriginFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilOverlayImage
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilOverlayImage
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilPopAttrib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilPopAttrib
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilPushAttrib
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilPushAttrib
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilRemoveLoad
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilRemoveLoad
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilRemoveSave
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilRemoveSave
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilResetMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilResetMemory
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilResetRead
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilResetRead
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilResetWrite
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilResetWrite
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilSave
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilSave
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilSaveImage
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilSaveImage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilSaveL
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_IL_nilSaveL
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilSavePal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilSavePal
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilSetData
 * Signature: (Ljava/nio/ByteBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_nilSetData
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilSetDuration
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilSetDuration
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilSetInteger
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilSetInteger
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilSetPixels
 * Signature: (IIIIIIIILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_nilSetPixels
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilSetString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilSetString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilShutDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_ilShutDown
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilTexImage
 * Signature: (IIIBIILjava/nio/ByteBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_nilTexImage
  (JNIEnv *, jclass, jint, jint, jint, jbyte, jint, jint, jobject, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilTypeFunc
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilTypeFunc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilLoadData
 * Signature: (Ljava/lang/String;IIIB)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilLoadData
  (JNIEnv *, jclass, jstring, jint, jint, jint, jbyte);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nilLoadDataL
 * Signature: (Ljava/nio/ByteBuffer;IIIIIB)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_nilLoadDataL
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jbyte);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    ilSaveData
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_IL_ilSaveData
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    initNativeStubs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_initNativeStubs
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    resetNativeStubs
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_resetNativeStubs
  (JNIEnv *, jclass, jclass);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nCreate
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_nCreate
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_lwjgl_devil_IL
 * Method:    nDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_IL_nDestroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
