/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_devil_ILU */

#ifndef _Included_org_lwjgl_devil_ILU
#define _Included_org_lwjgl_devil_ILU
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_devil_ILU_ILU_FILTER
#define org_lwjgl_devil_ILU_ILU_FILTER 9728L
#undef org_lwjgl_devil_ILU_ILU_NEAREST
#define org_lwjgl_devil_ILU_ILU_NEAREST 9729L
#undef org_lwjgl_devil_ILU_ILU_LINEAR
#define org_lwjgl_devil_ILU_ILU_LINEAR 9730L
#undef org_lwjgl_devil_ILU_ILU_BILINEAR
#define org_lwjgl_devil_ILU_ILU_BILINEAR 9731L
#undef org_lwjgl_devil_ILU_ILU_SCALE_BOX
#define org_lwjgl_devil_ILU_ILU_SCALE_BOX 9732L
#undef org_lwjgl_devil_ILU_ILU_SCALE_TRIANGLE
#define org_lwjgl_devil_ILU_ILU_SCALE_TRIANGLE 9733L
#undef org_lwjgl_devil_ILU_ILU_SCALE_BELL
#define org_lwjgl_devil_ILU_ILU_SCALE_BELL 9734L
#undef org_lwjgl_devil_ILU_ILU_SCALE_BSPLINE
#define org_lwjgl_devil_ILU_ILU_SCALE_BSPLINE 9735L
#undef org_lwjgl_devil_ILU_ILU_SCALE_LANCZOS3
#define org_lwjgl_devil_ILU_ILU_SCALE_LANCZOS3 9736L
#undef org_lwjgl_devil_ILU_ILU_SCALE_MITCHELL
#define org_lwjgl_devil_ILU_ILU_SCALE_MITCHELL 9737L
#undef org_lwjgl_devil_ILU_ILU_INVALID_ENUM
#define org_lwjgl_devil_ILU_ILU_INVALID_ENUM 1281L
#undef org_lwjgl_devil_ILU_ILU_OUT_OF_MEMORY
#define org_lwjgl_devil_ILU_ILU_OUT_OF_MEMORY 1282L
#undef org_lwjgl_devil_ILU_ILU_INTERNAL_ERROR
#define org_lwjgl_devil_ILU_ILU_INTERNAL_ERROR 1284L
#undef org_lwjgl_devil_ILU_ILU_INVALID_VALUE
#define org_lwjgl_devil_ILU_ILU_INVALID_VALUE 1285L
#undef org_lwjgl_devil_ILU_ILU_ILLEGAL_OPERATION
#define org_lwjgl_devil_ILU_ILU_ILLEGAL_OPERATION 1286L
#undef org_lwjgl_devil_ILU_ILU_INVALID_PARAM
#define org_lwjgl_devil_ILU_ILU_INVALID_PARAM 1289L
#undef org_lwjgl_devil_ILU_ILU_PLACEMENT
#define org_lwjgl_devil_ILU_ILU_PLACEMENT 1792L
#undef org_lwjgl_devil_ILU_ILU_LOWER_LEFT
#define org_lwjgl_devil_ILU_ILU_LOWER_LEFT 1793L
#undef org_lwjgl_devil_ILU_ILU_LOWER_RIGHT
#define org_lwjgl_devil_ILU_ILU_LOWER_RIGHT 1794L
#undef org_lwjgl_devil_ILU_ILU_UPPER_LEFT
#define org_lwjgl_devil_ILU_ILU_UPPER_LEFT 1795L
#undef org_lwjgl_devil_ILU_ILU_UPPER_RIGHT
#define org_lwjgl_devil_ILU_ILU_UPPER_RIGHT 1796L
#undef org_lwjgl_devil_ILU_ILU_CENTER
#define org_lwjgl_devil_ILU_ILU_CENTER 1797L
#undef org_lwjgl_devil_ILU_ILU_CONVOLUTION_MATRIX
#define org_lwjgl_devil_ILU_ILU_CONVOLUTION_MATRIX 1808L
#undef org_lwjgl_devil_ILU_ILU_VERSION_NUM
#define org_lwjgl_devil_ILU_ILU_VERSION_NUM 3554L
#undef org_lwjgl_devil_ILU_ILU_VENDOR
#define org_lwjgl_devil_ILU_ILU_VENDOR 7936L
/* Inaccessible static: created */
/* Inaccessible static: class_00024org_00024lwjgl_00024devil_00024ILU */
/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluAlienify
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluAlienify
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluBlurAvg
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluBlurAvg
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluBlurGaussian
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluBlurGaussian
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluBuildMipmaps
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluBuildMipmaps
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluColoursUsed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_ILU_iluColoursUsed
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluCompareImage
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluCompareImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluContrast
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluContrast
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluCrop
 * Signature: (IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluCrop
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluDeleteImage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILU_iluDeleteImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluEdgeDetectE
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluEdgeDetectE
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluEdgeDetectP
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluEdgeDetectP
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluEdgeDetectS
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluEdgeDetectS
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluEmboss
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluEmboss
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluEnlargeCanvas
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluEnlargeCanvas
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluEnlargeImage
 * Signature: (FFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluEnlargeImage
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluEqualize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluEqualize
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_devil_ILU_iluErrorString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluFlipImage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluFlipImage
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluGammaCorrect
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluGammaCorrect
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluGenImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_ILU_iluGenImage
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluGetImageInfo
 * Signature: (Lorg/lwjgl/devil/ILinfo;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILU_iluGetImageInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluGetInteger
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_ILU_iluGetInteger
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    niluGetIntegerv
 * Signature: (ILjava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILU_niluGetIntegerv
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_lwjgl_devil_ILU_iluGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluImageParameter
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILU_iluImageParameter
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILU_iluInit
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluInvertAlpha
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluInvertAlpha
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluLoadImage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_ILU_iluLoadImage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluMirror
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluMirror
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluNegative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluNegative
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluNoisify
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluNoisify
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluPixelize
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluPixelize
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluReplaceColour
 * Signature: (BBBF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluReplaceColour
  (JNIEnv *, jclass, jbyte, jbyte, jbyte, jfloat);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluRotate
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluRotate
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluSaturate1f
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluSaturate1f
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluSaturate4f
 * Signature: (FFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluSaturate4f
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluScale
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluScale
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluScaleColours
 * Signature: (FFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluScaleColours
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluSharpen
 * Signature: (FI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluSharpen
  (JNIEnv *, jclass, jfloat, jint);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluSwapColours
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluSwapColours
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    iluWave
 * Signature: (F)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lwjgl_devil_ILU_iluWave
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    initNativeStubs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILU_initNativeStubs
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    resetNativeStubs
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILU_resetNativeStubs
  (JNIEnv *, jclass, jclass);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    nCreate
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILU_nCreate
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_lwjgl_devil_ILU
 * Method:    nDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILU_nDestroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
